#!/bin/bash

apply-setting() {
    gsettings set "$(echo $1 | cut -d" " -f1)" "$(echo $1 | cut -d" " -f2)" "$(echo $1 | cut -d" " -f3-)"
}

if [[ $1 == "-" ]] || [ -z $1 ]
then
    while read line
    do
        apply-setting "$line"
    done
else
    while read line
    do
        apply-setting "$line"
    done < $1
fi

