#!/bin/bash
case "$1" in 
    *.png|*.jpg|*.jpeg|*.mkv|*.mp4) mediainfo "$1";;
    *.zip|*.tar|*.tar.gz|*.tar.bz2|*.tar.xz) als "$1";;
    *.md) glow -s dark "$1";;
    *.pdf) pdftotext "$1" -;;
    *.json) cat "$1" | jq -C;;
    *) highlight "$1" -O ansi --force;;
esac

